version: '3'

services:
  django-server:
    # replace username/repo:tag with your name and image details
    build: .
    command: >
      sh -c "python server/manage.py makemigrations
      && python server/manage.py migrate
      && python server/manage.py runserver 0.0.0.0:8000"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    container_name: dataset-server
    volumes:
      - .:/dataset-server
    ports:
      - 8000:8000
    networks:
      - webnet
networks:
  webnet:
